variables:
  SSH_USER: "vp-dbbackup"
  SSH_HOST: "10.94.61.126" 
 
stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - dean
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh $SSH_USER@$SSH_HOST "cd /opt/lampp/htdocs/safekup && git pull origin main && sudo /opt/lampp/lampp restart"
  only:
    - main
