variables:
  SSH_USER: "vp-dbbackup"
  SSH_HOST: "10.94.61.126"
  SSH_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEAnWAw9JG44xZ21gKUmfjNqT8Q+/8F284S7VhHRCsG+AZqTSlL28mO1VL8Z7ZiwtepUSDSULr7Jd2k+LHDBiYOLvTeEMAi8dcaZAnsqJA/UGCZ3jSHCpemI89kf2836wynknQuJLiuz7fPxP1J>
    -----END RSA PRIVATE KEY-----

stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - dean
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh $SSH_USER@$SSH_HOST "cd /opt/lampp/htdocs/safekup && git pull origin main && sudo /opt/lampp/lampp restart"
  only:
    - main
