variables:
  SSH_USER: "vp-dbbackup"
  SSH_HOST: "10.94.61.126"

stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - dean
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /tmp/private_key.pem
    - chmod 600 /tmp/private_key.pem
    - ssh-add /tmp/private_key.pem
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh $SSH_USER@$SSH_HOST "cd /opt/lampp/htdocs/safekup && git pull origin main && sudo /opt/lampp/lampp restart"
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      changes:
        - '**/*'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
