variables:
  SSH_USER: "vp-dbbackup"
  SSH_HOST: "10.94.61.126"
  SSH_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCdYDD0kbjjFnbWApSZ+M2pPxD7/wXbzhLtWEdEKwb4BmpNKUvbyY7VUvxntmLC16lRINJQuvsl3aT4scMGJg4u9N4QwCLx1xpkCeyokD9QYJneNIcKl6Yjz2R/bzfrDKeSdC4kuK7Pt8/E/UkAyTrCiAphb/kfJbJiNNuVwuQNCY2z5c8QRK0PCgqgvOirEmLLseRJrmNl6nRw7ZwMwGBLIZkAPqphxHxgMqAEXX//X4xq7aLrzXl/Fj9z26bDkpgXy9tyF+uWqRWjQHnuQfeog+EY0wOTgwGQJID8IaCDj5+/h2t2QS8/HIki+PRZqhR4qgpKmsxghhvQyI1Z4VizalGYpquGx4QIz+gTzIU3eajk0iwOh7KVwrFJcponwFnUHv3nrFasYA/ofHVm4wyAID4FpDjy4YTThCShQLNM+3qilvGh5I3aTDKInUsxmb2oAgpJfutwgFtm7Ag2c11PtLJeXjHmGL7TxawFyB35XISV5Cg/pOq4wTqBYWFTiRUWhAGv9r1Iq1leo6RockN4U2ggmETBVlerdIqM0Hk0dkJf3CSKE0u4mbBSF23zhifXYa1aL6cxKnO5riVoyWW66/tyiTGE8wF4Xe4MQxlgE06HamowwcKTINin3h/1V1d+CcpQoE1AqkodTal943UuUsdTa+hqjtY83WR0DeLvJw==
    -----END RSA PRIVATE KEY-----

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh $SSH_USER@$SSH_HOST "cd /opt/lampp/htdocs/safekup && git pull origin main && sudo /opt/lampp/lampp restart"
  only:
    - main
