variables:
  SSH_USER: "vp-dbbackup"
  SSH_HOST: "10.94.61.126"
  SSH_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA7VHt8NQOQkE1BqCqxJx5U+ZKb7wH4R0j5i6/Nu6HlB/NlJ7e
    bxDj9UvcmD8pXPiqlUZ0A0KOq5RZjDLtQZaDZmzwPxHpc5lTQZ6aKwF1ZCj0jErV
    HDFWYZFPm8FOcxZcFo16UFCyLPzYI1tw6XK7Zf1YbgK5zIY1E0z3DJiXwKh0sPQG
    rQz5w+XSr76RsU6thBhv0sb5PaEZVzuQz9G5Gg6Jt4n57H9TbN2RmA/xqT7d0Dr9
    FCAdTbHQC8Wk93OG8hKhZ6eiP4kTf6zA9YrHZZV9Dzr9dqET2o1g1p+G6Xk5dN4D
    7YlNmiI1bh/aUQC9hUbN/h9yD2ahUj45HfSRIK6LBkzoyDByC0D8TTtYuqf/OwQ1
    jFJdRrU8j09Op4SZNGwD5gQKBgQClSx8u+dIIE0yB8j4T1LHl8nHqVXswB+MPbu
    kYCTd16A3+El9q9UHZsxl/ITz0k4f9k2Uz/Dpe4dgoZn6p8N8rOeL23tnHpq3nL7
    5P6KrZjD6Dl0y4NU8PU6owjB6bGCq8M6O6+kjKz2wZ5ozgTcIkOn0OCkJ/RI/xwT
    umGqkD6D/f8tq/Q+i1b3DW/Zb3A0QxE59GjTiQkQKBgQC6eR7yfr3qlj2v8qj+5I
    a6hld4n0/XBdUQxAeVjqHQlLHZBg4uMFCcC4E3PH6ZRxCF+X7F2A5oh9gXtN3MD
    8bA4U1kxfFhLgQfGfXxkkDtzrk/1NzXJHLZw7HpGVjPbtTzMdd7lE8oFj+TX+8Y
    SxZtnK0QKBgE7V2W9CNUmb7Ck2xY4X8eyGHrFkgD4WyAkGeXg8ab+I6FP5dCT4Op
    D7A0Tgtph3b/Jzq1SclFwG8eDBTg0sm5Pa/7WfL8K1PPTdKoNIf5eoc5sblQsMyS
    O7wZLO0iTkNzp96YZM2uRUW6WgTk2IPJvqFyzGqodt9seV1EVbVX7pYj4b9ryzx
    -----END RSA PRIVATE KEY-----
  
stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - dean
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh $SSH_USER@$SSH_HOST "cd /opt/lampp/htdocs/safekup && git pull origin main && sudo /opt/lampp/lampp restart"
  only:
    - main
