version: "3.9"

services:
  safekup:
    image: php:8.2-apache
    container_name: safekup-new
    ports:
      - "8081:80"
    volumes:
      - /mnt/c/projetoshu/safekup-new:/var/www/html
    working_dir: /var/www/html
    environment:
      TZ: America/Sao_Paulo

  safekup-laravel:
    build:
      context: .
      dockerfile: docker/laravel.Dockerfile
    container_name: safekup-laravel
    ports:
      - "8082:80"
    volumes:
      - ./safekup-laravel:/var/www/html
    working_dir: /var/www/html
    environment:
      TZ: America/Sao_Paulo
      APACHE_DOCUMENT_ROOT: /var/www/html/public
