version: "3.9"
services:
  safekup:
    image: php:8.2-apache
    container_name: safekup
    ports:
      - "8081:80"
    volumes:
      - "C:\projetosHU\safekup-new:/var/www/html"
    working_dir: /var/www/html
    environment:
      TZ: America/Sao_Paulo
